apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-trust
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: cert-manager-trust
    repoURL: https://charts.jetstack.io
    targetRevision: v0.2.1
  syncPolicy:
    automated: {}
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
