apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certmanager
  namespace: argocd
spec:
  destination:
    namespace: certmanager
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: cert-manager
    helm:
      parameters:
        - name: installCRDs
          value: 'true'
      valueFiles:
        - values.yaml
    repoURL: https://charts.jetstack.io
    targetRevision: v1.13.1
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
