proxmox:
    token_id: ENC[AES256_GCM,data:Ou8g0fNZDzk4qyYns4J8hJuD,iv:laxRqwNXVItvCPIpu3v8H7/+U2nxwxmtoJpC4nnPZ4Y=,tag:gHCx/7kB9Tk2CyhBKAOD6A==,type:str]
    api_url: ENC[AES256_GCM,data:Gs9TD74xbSU42rOh6On8LNCzQUlgw81DfR6Z2HVCPLQh3us=,iv:sX3abcTW4+TORDffMBu8Q5OE9t+saeN8gfAps8KEo8Y=,tag:n26LSt88OSjv7cdZFn+mbg==,type:str]
    token_secret: ENC[AES256_GCM,data:T8t4rDJ3V/uRtanTD6AjWfqoPJbNCcHrtp4j8LoQVwAlETsv,iv:e72/M4tzM5zFn58KP2R3AFSOlQfIjnM9OY2Idbve6vg=,tag:h4/GkK6cLV8QcqIr7WiKIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19t2al77nhtazslzknxrxffdjf27fqyehejna7sxt2e97fwwx5pls5clc4s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWGU4T0JnNzFKNnNIZ2o4
            amh0Rk5nWjE2RFI0WXlxQmlidnp5MzBYWkY4CmtQVC9RUEpoOUFxNnRSWG9QbHZx
            NUVibEsrN0JoZWh0Uy9EYWdnNUVrczAKLS0tIEMxNEVFUmo5VkFQMGY1NUdPUFY2
            MjJyNGNCallRTmlYSkdYY1ZCMVlpTTAK02AkAHuYghdGT1SmHLylczD/ZYQb682a
            XVeI8OcBbm3XmEQcJ3skcVc08DtIE1huWXdzrbv/lVQNZxdM4CC00Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-17T10:12:40Z"
    mac: ENC[AES256_GCM,data:c1m7T3nLzYSbz5sj8MzzKayICXshgxcrmbgAZv1b7d6klln4ufto067KdqzE8/6ces5LaJSEv37s7vqaDf6mAbJk696BLFOeE9erAeS4sk8hliL7023ob3t9AelyJM2uXO6vsDPiZFEPD3z6vGaJISYQqFaz0rgrFDTzL9cMgac=,iv:3y5pyZy8SIrtAoG2ecxjXbK19t8qxWmTmcL2jW7RhEc=,tag:6mKZK4s/3Y7uXnW5jvF29A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
