grafana:
    password: ENC[AES256_GCM,data:r9OVGaURUY2b4bQnDTZoJ5HtLyL/vMFSNGPv3g8VFQH5R8X6OjB+YlTM2g==,iv:cn2Cg9Hz7CcsSppJ5J2Ahnwza2FCEuqxkM1o6NrrWcM=,tag:Y3XzZlOsovvwL0h8BQCQVw==,type:str]
cloudflare:
    token: ENC[AES256_GCM,data:pJoxHwhGJxr3qVPG/qpUi4O9AYUQ5nFnVIH0kE4p/bjXgQz5KR8i4g==,iv:KpjYRVCTy4EuOZUfXEeXp9IGOQO4MHnZR0hTsayKetU=,tag:VarpE4FD94MveKWPVGD+sg==,type:str]
    zone_id: ENC[AES256_GCM,data:z4ElSy5+3Su91j9uqBU58qiLapa/fF5wn0NfK8rpjew=,iv:JOZUfvBHDxkFfLSWcBY8VLqxv8F9j9J3Bleh95rtYXc=,tag:KRl+sGWQ3AnDLfFymZCTCA==,type:str]
    account_id: ENC[AES256_GCM,data:Z9+OL9RWNmEGDcJnB/Q1otIYzXHctCiWIOTXf7ep31s=,iv:ZugDhE2Ohn4BwGaIiY6CG2NTJZOEI1t8uzsUuOvyIj8=,tag:BB+dNCAYZbnEB0VL1qt96w==,type:str]
    zone: ENC[AES256_GCM,data:gEi+NDI0qm1EoA==,iv:INltNytbXxCAk4dpAoAdYGUTAXouan5RbyKsA6+fqU4=,tag:jDn7u+qTjqPYTvN2EHgsHA==,type:str]
    email: ENC[AES256_GCM,data:vG88IoINFmMYKG2hG7B6pXgxMzsu,iv:HRDj6uVqbB1nIW6oA3PjHtUJIiwJAw59q9Vx42hzN/c=,tag:PdUg1RkBE5XbY+N2dfmMdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19t2al77nhtazslzknxrxffdjf27fqyehejna7sxt2e97fwwx5pls5clc4s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ejdUamlrdHNhSlltVElE
            UktJb04zQURQOG1MZzZpVVZZYUNqd1M3V1QwCkM5b1JRQ3BxYWhsODFJeVRUOXJJ
            aTlPUWhndmVJV2crSjA2Q3o5TVpqckEKLS0tIFo3WC9VajAxZTMvSnZ4S1haQzA0
            S1psb2E5RzFhT3I2aFRwWDdEeVdtcjAKN44R7jNGm0/+8JlucwrLQgpfGmN1Svaz
            0gEzeorwOikQkwQjZn6TtyOWC2Whr7S8UIVVd3hhAZUEohrtTzmGcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-20T15:46:46Z"
    mac: ENC[AES256_GCM,data:AsZK5yAiV+2zmloQk0omTtF9K7CxvJO+IoVBop6jzrUdQ8NbCuIJoY7jYN05OWGVS/5eTuq0cvFLQRq5tqj3HaFhou/sT/ZDjFd5s/oG6Y+tpdwoBJW4fuSHbvcrOoax9qw5HblHwZTsiLVHPQ6Bc23EqW+jUEId27CRpgVF0r0=,iv:QMy21aPO6wmcx7jjolmzk0kLU5Xr4Zm7h382EwgC07M=,tag:/P1lxVg1f6doYCv+qHTV8w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
