---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-root
  namespace: cert-manager
spec:
  isCA: true
  commonName: root.linkerd.cluster.local
  secretName: linkerd-trust-anchor
  duration: 43800h # 5y
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  usages:
    - cert sign
    - crl sign
