prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 10Gi
grafana:
  additionalDataSources:
    - name: loki
      type: loki
      url: http://loki-gateway.loki.svc
