---
- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes

- name: Enable IPv6 forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: yes
  when: ansible_all_ipv6_addresses

- name: Increase UDP Buffer Sizes
  sysctl:
    name: "{{ item }}"
    value: "2500000"
    state: present
    reload: yes
  loop:
    - net.core.rmem_max
    - net.core.wmem_max
