---
- name: Enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes

- name: Enable IPv6 forwarding
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: yes
  when: ansible_all_ipv6_addresses

- name: Increase UDP Buffer Sizes
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "2500000"
    state: present
    reload: yes
  loop:
    - net.core.rmem_max
    - net.core.wmem_max

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Install nfs-common
  apt:
    name: nfs-common
    state: present
