apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shadowtest
  namespace: argocd
spec:
  destination:
    namespace: shadowtest
    server: https://kubernetes.default.svc
  project: default
  source:
    path: shadowtest
    repoURL: https://github.com/jadolg/ShadowTest
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
